#1807 - Sidebar view updates
equinor/witsml-explorer pull request #1892
Opened 2023-05-23 04:27 UTC by basim-rauf

[//]: # (Request Template Witsml Explorer)

[//]: # (Thank you for contributing to WITSML Explorer! Before submitting this PR, please fill in the following template.)

## Fixes

[//]: # (Write the GitHub issue number starting with #, or, for Equinor only, the Jira issue number starting with WE-)

This pull request fixes #1828 

## Description

[//]: # (Please include a written summary of the changes and which issue is fixed. List any dependencies that are required for this change._)
Updates to Sidebar view. Adding beat icon and removing the lightning icon from sidebar

## Type of change

[//]: # (Mark any of the types of change that apply.)

* [ ] Bugfix
* [ ] New feature (non-breaking change which adds functionality)
* [x] Enhancement of existing functionality
* [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
* [ ] This change requires a documentation update

## Impacted Areas in Application

[//]: # (List general components of the application that this PR will affect)

* [x] Frontend
* [ ] API
* [ ] WITSML
* [ ] Other (please describe)

## Checklist:

[//]: # (Please tick all the boxes or remove the ones that aren't needed and explain why)

*Communication*
* [ ] I have made corresponding changes to the documentation
* [x] PR affects application security

*Code quality*
* [x] I have self-reviewed my code
* [x] No new warnings are generated

*Test coverage*
* [x] New code is covered by passing tests

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

2023-05-23 10:04 UTC, janburak commented on Src/WitsmlExplorer.Frontend/components/GlobalStyles.tsx
> +  .sideBarView  .MuiTreeItem-root {
Any reason these styles are here instead of the existing SidebarTreeView style on line 54 in Sidebar.tsx?

2023-05-23 10:06 UTC, janburak commented on Src/WitsmlExplorer.Frontend/components/Sidebar/SearchFilter.tsx
> +  padding-right: 6px;
padding for all directions is already defined on line 73 so adding another line for just padding-right is superfluous

2023-05-23 10:08 UTC, janburak commented on Src/WitsmlExplorer.Frontend/components/Sidebar/TreeItem.tsx
> +          {isActive && labelText == "Logs" && <Icon name="beat" color={colors.interactive.primaryResting} style={{ position: "absolute", right: "-25px", top: "6px" }} />}
isActive should be sufficient to determine whether the beat icon is show. If necessary, rename `isActive` to `showBeat `and move out the logic of computing `showBeat` outside of this component

2023-05-23 10:09 UTC, janburak commented on Src/WitsmlExplorer.Frontend/components/Sidebar/TreeItem.tsx
> +              {labelText} {isLoading && <DotProgress color={"primary"} size={32} />}
`DotProgress` is no longer showing when the `labelText` is too long

2023-05-23 10:14 UTC, janburak requested changes
The requested changes have been specified in the individual comments.
Additionally, as confirmed by Thomas, wellbores should also show an active/inactive indicator as specified in the design.
![image](https://github.com/equinor/witsml-explorer/assets/66632214/59aff5e5-7ab3-436b-a02f-f44b29a85a87)

2023-06-06 13:53 UTC, janburak commented
The icons do not line up vertically like in the design. Would it be possible to fix it? Looks good other than that.
![image](https://github.com/equinor/witsml-explorer/assets/66632214/0aae91ed-6057-4939-9136-f6de1cf97043)

2023-06-07 05:01 UTC, basim-rauf commented
> 

I've fixed the alignment of icons

2023-06-07 09:27 UTC, janburak approved these changes
- [X] Read issue and PR
- [X] Pulled branch and manually tested
- [X] Verify that PR resolves issue
- [X] Reviewed the code

2023-06-07 09:28 UTC, merged