Refresh button for (sub) objects #2083
equinor/witsml-explorer pull request #2110
Opened 2023-10-27 13:27 UTC by robertbasti

[//]: # (Request Template Witsml Explorer)

[//]: # (Thank you for contributing to WITSML Explorer! Before submitting this PR, please fill in the following template.)

## Fixes
 This pull request fixes https://github.com/equinor/witsml-explorer/issues/2083

## Description
- added refresh button also to objects including context menu

[//]: # (Please include a written summary of the changes and which issue is fixed. List any dependencies that are required for this change._)

## Type of change

[//]: # (Mark any of the types of change that apply.)

* [ ] Bugfix
* [ ] New feature (non-breaking change which adds functionality)
* [x] Enhancement of existing functionality
* [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
* [ ] This change requires a documentation update

## Impacted Areas in Application

[//]: # (List general components of the application that this PR will affect)

* [x] Frontend
* [ ] API
* [ ] WITSML
* [ ] Other (please describe)

## Checklist:

[//]: # (Please tick all the boxes or remove the ones that aren't needed and explain why)

*Communication*
* [ ] I have made corresponding changes to the documentation
* [ ] PR affects application security

*Code quality*
* [x] I have self-reviewed my code
* [x] No new warnings are generated

*Test coverage*
* [] New code is covered by passing tests

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

2023-11-01 09:11 UTC, eliasbruvik requested changes

2023-11-01 09:11 UTC, eliasbruvik commented on Src/WitsmlExplorer.Frontend/components/ContentViews/table/Panel.tsx
Instead of introducing `showObjectRefresh`, use `showRefresh`. In the `onClickRefresh`, you can then add a check `else if (currentSelected === selectedObject)` to call `refreshObject()`.

2023-11-01 09:11 UTC, eliasbruvik commented on Src/WitsmlExplorer.Frontend/components/ContentViews/table/Panel.tsx
> +    const wellboreObjects = await ObjectService.getObjects(wellUid, wellboreUid, selectedObjectGroup, abortRefreshControllerRef.current.signal);
I think you only should refresh the current object, not all objects.

2023-11-01 13:04 UTC, robertbasti commented on Src/WitsmlExplorer.Frontend/components/ContextMenus/ObjectMenuItems.tsx
I'm not sure how to do that.

2023-11-01 17:57 UTC, robertbasti commented on Src/WitsmlExplorer.Frontend/components/ContentViews/table/Panel.tsx
solved

2023-11-01 17:58 UTC, robertbasti commented on Src/WitsmlExplorer.Frontend/components/ContentViews/table/Panel.tsx
> +    const wellboreObjects = await ObjectService.getObjects(wellUid, wellboreUid, selectedObjectGroup, abortRefreshControllerRef.current.signal);
solved

2023-11-01 17:58 UTC, robertbasti commented on Src/WitsmlExplorer.Frontend/components/ContextMenus/ObjectMenuItems.tsx
solved

2023-11-02 14:45 UTC, eliasbruvik approved these changes
- [x] Read issue and PR
- [x] Pulled branch and manually tested
- [x] Verify that PR resolves issue
- [x] Reviewed the code

2023-11-02 14:46 UTC, merged