FIX-2109 Add icon to open self-closing tags in QueryView
equinor/witsml-explorer pull request #2111
Opened 2023-10-27 13:39 UTC by eliasbruvik

[//]: # (Request Template Witsml Explorer)

[//]: # (Thank you for contributing to WITSML Explorer! Before submitting this PR, please fill in the following template.)

## Fixes

[//]: # (Write the GitHub issue number starting with #, or, for Equinor only, the Jira issue number starting with WE-)

This pull request fixes #2109 

## Description

Added a icon on lines with a self-closing tag. Clicking the icon expands the tag and places the cursor between the opening and closing tag.

## Type of change

[//]: # (Mark any of the types of change that apply.)

* [ ] Bugfix
* [ ] New feature (non-breaking change which adds functionality)
* [ ] Enhancement of existing functionality
* [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
* [ ] This change requires a documentation update

## Impacted Areas in Application

[//]: # (List general components of the application that this PR will affect)

* [ ] Frontend
* [ ] API
* [ ] WITSML
* [ ] Other (please describe)

## Checklist:

[//]: # (Please tick all the boxes or remove the ones that aren't needed and explain why)

*Communication*
* [ ] I have made corresponding changes to the documentation
* [ ] PR affects application security

*Code quality*
* [ ] I have self-reviewed my code
* [ ] No new warnings are generated

*Test coverage*
* [ ] New code is covered by passing tests

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

2023-10-30 09:57 UTC, janmarius requested changes
Nice work! I think this new feature would be very useful in the query view. I have made a few comments regarding the types.

2023-10-30 09:57 UTC, janmarius commented on Src/WitsmlExplorer.Frontend/components/QueryEditor.tsx
> +      editor.renderer.on("afterRender", (_: any, renderer: any) => updateLinesWithWidgets(editor, renderer));
I recommend fixing the types, cleaning up `any` types later can be tedious.
Suggested fix:
```js
import { Ace } from "ace-builds";

  const onLoad = (editor: Ace.Editor) => {
    editor.renderer.setPadding(10);
    editor.renderer.setScrollMargin(10, 0, 0, 0);
    if (readonly) {
      editor.renderer.hideCursor();
    } else {
      editor.completers = [customCompleter];
      editor.renderer.on("afterRender", (_: string, renderer: Ace.VirtualRenderer) => updateLinesWithWidgets(editor, renderer));
    }
  };
```
Could you please verify if the method `hideCursor()` is the correct one to use?

2023-10-30 09:57 UTC, janmarius commented on Src/WitsmlExplorer.Frontend/components/QueryEditorWidgetUtils.tsx
> +const onClickOpenTag = (editor: any, row: number) => {
Fix `any` type. `editor: Ace.Editor`

2023-10-30 09:57 UTC, janmarius commented on Src/WitsmlExplorer.Frontend/components/QueryEditorWidgetUtils.tsx
> +  session.replace({ start: { row, column: 0 }, end: { row, column: lineText.length } }, newText);
When I tried to fix the types, the `session.replace()` method complained. Another method in [ace-builds/ace.d.ts](https://github.com/ajaxorg/ace-builds/blob/master/ace.d.ts) may be more suitable. We are now working with `Ace.EditSession`.

2023-10-30 09:57 UTC, janmarius commented on Src/WitsmlExplorer.Frontend/components/QueryEditorWidgetUtils.tsx
> +export const updateLinesWithWidgets = (editor: any, renderer: any) => {
Types: `editor: Ace.Editor, renderer: Ace.VirtualRenderer`

2023-10-30 09:57 UTC, janmarius commented on Src/WitsmlExplorer.Frontend/components/QueryEditorWidgetUtils.tsx
> +const updateWidgets = (editor: any, renderer: any) => {
Types: `editor: Ace.Editor, renderer: Ace.VirtualRenderer`

2023-10-30 09:57 UTC, janmarius commented on Src/WitsmlExplorer.Frontend/components/QueryEditorWidgetUtils.tsx
> +  const first = config.firstRow;
I suggest using more descriptive names like `firstRow` and `lastRow` to improve readability.

2023-10-31 14:21 UTC, eliasbruvik commented
I have tried to find the types instead of using any, but I could not find the correct types to use. The types that I thought would work were missing several methods that I am using. So for now we'll leave the types out. If the type libraries are updated with the methods later, we could use it at a later point.

2023-10-31 14:21 UTC, eliasbruvik commented on Src/WitsmlExplorer.Frontend/components/QueryEditorWidgetUtils.tsx
> +  const first = config.firstRow;
Fixed

2023-10-31 14:23 UTC, janmarius commented on Src/WitsmlExplorer.Frontend/components/QueryEditor.tsx
> +      editor.renderer.on("afterRender", (_: any, renderer: any) => updateLinesWithWidgets(editor, renderer));
We had a discussion and decided to skip this task because it was complicated due to issues with the package.

2023-10-31 14:23 UTC, janmarius commented on Src/WitsmlExplorer.Frontend/components/QueryEditorWidgetUtils.tsx
> +  session.replace({ start: { row, column: 0 }, end: { row, column: lineText.length } }, newText);
We had a discussion and decided to skip this task because it was complicated due to issues with the package.

2023-10-31 14:23 UTC, janmarius commented on Src/WitsmlExplorer.Frontend/components/QueryEditorWidgetUtils.tsx
> +export const updateLinesWithWidgets = (editor: any, renderer: any) => {
We had a discussion and decided to skip this task because it was complicated due to issues with the package.

2023-10-31 14:23 UTC, janmarius commented on Src/WitsmlExplorer.Frontend/components/QueryEditorWidgetUtils.tsx
> +const updateWidgets = (editor: any, renderer: any) => {
We had a discussion and decided to skip this task because it was complicated due to issues with the package.

2023-10-31 14:24 UTC, janmarius commented on Src/WitsmlExplorer.Frontend/components/QueryEditorWidgetUtils.tsx
> +const onClickOpenTag = (editor: any, row: number) => {
We had a discussion and decided to skip this task because it was complicated due to issues with the package.

2023-10-31 14:25 UTC, janmarius approved these changes
*Reviewer checklist*
- [x] Read issue and PR
- [x] Pulled branch and manually tested
- [x] Verify that PR resolves issue
- [x] Reviewed the code

2023-10-31 14:35 UTC, merged