FIX-2009 Update logCurveInfo properties
equinor/witsml-explorer pull request #2129
Opened 2023-11-13 10:48 UTC by jaroslavbliznak

[//]: # (Request Template Witsml Explorer)

[//]: # (Thank you for contributing to WITSML Explorer! Before submitting this PR, please fill in the following template.)

## Fixes

[//]: # (Write the GitHub issue number starting with #, or, for Equinor only, the Jira issue number starting with WE-)

This pull request fixes #2009 

## Description

[//]: # (Please include a written summary of the changes and which issue is fixed. List any dependencies that are required for this change._)

## Type of change

[//]: # (Mark any of the types of change that apply.)

* [ ] Bugfix
* [X] New feature (non-breaking change which adds functionality)
* [ ] Enhancement of existing functionality
* [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
* [ ] This change requires a documentation update

## Impacted Areas in Application

[//]: # (List general components of the application that this PR will affect)

* [X] Frontend
* [X] API
* [ ] WITSML
* [ ] Other (please describe)

## Checklist:

[//]: # (Please tick all the boxes or remove the ones that aren't needed and explain why)

*Communication*
* [ ] I have made corresponding changes to the documentation
* [ ] PR affects application security

*Code quality*
* [X] I have self-reviewed my code
* [X] No new warnings are generated

*Test coverage*
* [X] New code is covered by passing tests

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

2023-11-17 09:04 UTC, janmarius requested changes
I added suggestions and comments on minor issues. During testing, I also noticed changing the index curve was possible. Is this expected behavior?

2023-11-17 09:04 UTC, janmarius commented on Tests/WitsmlExplorer.IntegrationTests/Api/Workers/RenameMnemonicWorkerTests.cs
>  using WitsmlExplorer.Api.Models;
Do we also need to change the name of this file?

2023-11-17 09:04 UTC, janmarius commented on Src/WitsmlExplorer.Api/Workers/Modify/ModifyLogCurveInfoWorker.cs
> +                var updatedMnemonics = string.Join(",", GetMnemonics(logHeader, job.LogCurveInfo.Mnemonic));
Is it appropriate to use `DataSeparator` found in `CommonConstants.cs` in this context?

2023-11-17 09:04 UTC, janmarius commented on Src/WitsmlExplorer.Api/Workers/Modify/ModifyLogCurveInfoWorker.cs
> +                var updatedUnits = string.Join(",", GetUnits(logHeader, job.LogCurveInfo.Unit));
`DataSeparator`?

2023-11-17 09:04 UTC, janmarius commented on Src/WitsmlExplorer.Api/Workers/Modify/ModifyLogCurveInfoWorker.cs
> +            var indexCurveUnit = log.LogCurveInfo.FirstOrDefault(x => x.Mnemonic == log.IndexCurve.Value)?.Unit ?? CommonConstants.DefaultUnit;
Has the team discussed and approved setting non-existing units to 'unitless' when no unit is provided for the mnemonic?

2023-11-17 09:04 UTC, janmarius commented on Src/Witsml/CommonConstants.cs
> +    public const string DefaultUnit = "unitless";
Can you please confirm if this is the team's approved default behavior?

2023-11-17 09:04 UTC, janmarius commented on Tests/WitsmlExplorer.Api.Tests/Workers/ModifyLogCurveInfoWorkerTests.cs
> +            Assert.Equal(expectedCurveDescription, updatedLogs.First().Logs.First().LogCurveInfo.First().CurveDescription);
Would using `FirstOrDefault()` be a better approach in this particular situation, considering that it does not throw any errors?

2023-11-17 09:04 UTC, janmarius commented on Tests/WitsmlExplorer.Api.Tests/Workers/ModifyLogCurveInfoWorkerTests.cs
> +            Assert.Equal(expectedMnemonic, updatedLogs.First().Logs.First().LogCurveInfo.First().Mnemonic);
FirstOrDefault?

2023-11-17 09:04 UTC, janmarius commented on Src/WitsmlExplorer.Frontend/components/Modals/LogCurveInfoPropertiesModal.tsx
> +                helperText={editableLogCurveInfo.unit == null || editableLogCurveInfo.unit.length === 0 ? "A unit cannot be empty." : ""}
Doesn't a unit have a maximum length?

2023-11-23 08:38 UTC, jaroslavbliznak commented on Tests/WitsmlExplorer.IntegrationTests/Api/Workers/RenameMnemonicWorkerTests.cs
>  using WitsmlExplorer.Api.Models;
Renamed.

2023-11-23 08:39 UTC, jaroslavbliznak commented on Src/WitsmlExplorer.Api/Workers/Modify/ModifyLogCurveInfoWorker.cs
> +                var updatedMnemonics = string.Join(",", GetMnemonics(logHeader, job.LogCurveInfo.Mnemonic));
Fixed.

2023-11-23 08:39 UTC, jaroslavbliznak commented on Src/WitsmlExplorer.Api/Workers/Modify/ModifyLogCurveInfoWorker.cs
> +                var updatedUnits = string.Join(",", GetUnits(logHeader, job.LogCurveInfo.Unit));
Fixed.

2023-11-23 08:43 UTC, jaroslavbliznak commented on Src/WitsmlExplorer.Api/Workers/Modify/ModifyLogCurveInfoWorker.cs
> +            var indexCurveUnit = log.LogCurveInfo.FirstOrDefault(x => x.Mnemonic == log.IndexCurve.Value)?.Unit ?? CommonConstants.DefaultUnit;
I discussed it with Elias. I removed 'unitless' and in this case, it is relevant not to specify the default unit. (It means an empty value will be used.)

2023-11-23 08:44 UTC, jaroslavbliznak commented on Src/Witsml/CommonConstants.cs
> +    public const string DefaultUnit = "unitless";
DefaultUnit was removed.

2023-11-23 08:44 UTC, jaroslavbliznak commented on Tests/WitsmlExplorer.Api.Tests/Workers/ModifyLogCurveInfoWorkerTests.cs
> +            Assert.Equal(expectedCurveDescription, updatedLogs.First().Logs.First().LogCurveInfo.First().CurveDescription);
Fixed.

2023-11-23 08:44 UTC, jaroslavbliznak commented on Tests/WitsmlExplorer.Api.Tests/Workers/ModifyLogCurveInfoWorkerTests.cs
> +            Assert.Equal(expectedMnemonic, updatedLogs.First().Logs.First().LogCurveInfo.First().Mnemonic);
Fixed.

2023-11-23 08:44 UTC, jaroslavbliznak commented on Src/WitsmlExplorer.Frontend/components/Modals/LogCurveInfoPropertiesModal.tsx
> +                helperText={editableLogCurveInfo.unit == null || editableLogCurveInfo.unit.length === 0 ? "A unit cannot be empty." : ""}
Fixed.

2023-11-23 08:45 UTC, jaroslavbliznak commented
I have fixed the modification if it is the index curve. In this case, it is not possible to rename the mnemonic.

2023-11-23 12:41 UTC, janmarius requested changes
I am unable to change the name of the mnemonic (error shown in image below). Additionally, it is still possible to modify the unit of the index curve. Should this be allowed?

![image](https://github.com/equinor/witsml-explorer/assets/48485965/7f873733-071a-4fea-809e-c58189259dd1)

2023-11-23 13:22 UTC, jaroslavbliznak commented
This is an error with overlapping indexes during editing, and it only occurs on the test server for Petrolink (https://eqwitsml.demo.petrolink.net/Petrovault/WITSML/WMLS.asmx). Asbjørn has already reported a message about it to them. It should work fine on other servers. The unit should be editable for the index curve as well.

2023-11-23 13:27 UTC, janmarius approved these changes
*Reviewer checklist*
- [x] Read issue and PR
- [x] Pulled branch and manually tested
- [x] Verify that PR resolves issue
- [x] Reviewed the code

2023-11-23 13:28 UTC, merged