FIX-2093 Edit Curves
equinor/witsml-explorer pull request #2138
Opened 2023-11-22 11:12 UTC by eliasbruvik

[//]: # (Request Template Witsml Explorer)

[//]: # (Thank you for contributing to WITSML Explorer! Before submitting this PR, please fill in the following template.)

## Fixes

[//]: # (Write the GitHub issue number starting with #, or, for Equinor only, the Jira issue number starting with WE-)

This pull request fixes #2093 

## Description

[//]: # (Please include a written summary of the changes and which issue is fixed. List any dependencies that are required for this change._)

Added the possibility to change the selected mnemonics while in CurveValuesView.

## Type of change

[//]: # (Mark any of the types of change that apply.)

* [ ] Bugfix
* [ ] New feature (non-breaking change which adds functionality)
* [ ] Enhancement of existing functionality
* [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
* [ ] This change requires a documentation update

## Impacted Areas in Application

[//]: # (List general components of the application that this PR will affect)

* [ ] Frontend
* [ ] API
* [ ] WITSML
* [ ] Other (please describe)

## Checklist:

[//]: # (Please tick all the boxes or remove the ones that aren't needed and explain why)

*Communication*
* [ ] I have made corresponding changes to the documentation
* [ ] PR affects application security

*Code quality*
* [ ] I have self-reviewed my code
* [ ] No new warnings are generated

*Test coverage*
* [ ] New code is covered by passing tests

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

2023-11-22 15:09 UTC, janmarius requested changes

2023-11-22 15:09 UTC, janmarius commented on Src/WitsmlExplorer.Frontend/components/ContentViews/EditSelectedLCI.tsx
> +const EditSelectedLCI = (props: EditSelectedLCIProps): React.ReactElement => {
Abbreviations like LCI can be confusing for new developers. I suggest changing it to `EditSelectedLogCurveInfo`.

2023-11-22 15:09 UTC, janmarius commented on Src/WitsmlExplorer.Frontend/components/ContentViews/EditSelectedLCI.tsx
> +  const submitLCI = () => {
`submitLCI` -> `submitLogCurveInfo`

2023-11-22 15:09 UTC, janmarius commented on Src/WitsmlExplorer.Frontend/components/ContentViews/EditSelectedLCI.tsx
> +    const filteredLCI = logCurveInfo.filter((lci) => selectedMnemonics.includes(lci.mnemonic));
`filteredLCI` -> `filteredLogCurveInfo`

2023-11-23 06:56 UTC, eliasbruvik commented on Src/WitsmlExplorer.Frontend/components/ContentViews/EditSelectedLCI.tsx
> +const EditSelectedLCI = (props: EditSelectedLCIProps): React.ReactElement => {
Removed all abbreviations except for in arrow functions.

2023-11-23 08:10 UTC, janmarius approved these changes
*Reviewer checklist*
- [x] Read issue and PR
- [x] Pulled branch and manually tested
- [x] Verify that PR resolves issue
- [x] Reviewed the code

2023-11-23 09:12 UTC, merged