FIX-2296 Move styled buttons
equinor/witsml-explorer pull request #2298
Opened 2024-03-13 08:36 UTC by eliasbruvik

[//]: # (Request Template Witsml Explorer)

[//]: # (Thank you for contributing to WITSML Explorer! Before submitting this PR, please fill in the following template.)

## Fixes

[//]: # (Write the GitHub issue number starting with #, or, for Equinor only, the Jira issue number starting with WE-)

This pull request fixes #2296

## Description

[//]: # (Please include a written summary of the changes and which issue is fixed. List any dependencies that are required for this change._)

Moved the common styled buttons to StyledComponents.

## Type of change

[//]: # (Mark any of the types of change that apply.)

* [ ] Bugfix
* [ ] New feature (non-breaking change which adds functionality)
* [ ] Enhancement of existing functionality
* [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
* [ ] This change requires a documentation update

## Impacted Areas in Application

[//]: # (List general components of the application that this PR will affect)

* [x] Frontend
* [ ] API
* [ ] WITSML
* [ ] Other (please describe)

## Checklist:

[//]: # (Please tick all the boxes or remove the ones that aren't needed and explain why)

*Communication*
* [ ] I have made corresponding changes to the documentation
* [ ] PR affects application security

*Code quality*
* [x] I have self-reviewed my code
* [x] No new warnings are generated

*Test coverage*
* [ ] New code is covered by passing tests

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

2024-03-13 10:18 UTC, janmarius requested changes
Since this PR does not create one generic Button for the whole application, I think we should create another issue to solve this. This will make it a lot easier to use different variations of the EDS-Button in different places in the application.

I made a few comments, but overall, it looks good. Nice cleanup.

2024-03-13 10:18 UTC, janmarius commented on Src/WitsmlExplorer.Frontend/components/ContentViews/EditNumber.tsx
> +      <OutlinedIconButton
This should be changed to `StyledGhostButton` to have consistent styling for all icon buttons.

2024-03-13 10:18 UTC, janmarius commented on Src/WitsmlExplorer.Frontend/components/ContentViews/EditSelectedLogCurveInfo.tsx
> +          <OutlinedIconButton
This should be changed to StyledGhostButton to have consistent styling for all icon buttons.

2024-03-13 10:18 UTC, janmarius commented on Src/WitsmlExplorer.Frontend/components/ContentViews/EditSelectedLogCurveInfo.tsx
>              <Icon size={16} name={isEdited ? "arrowForward" : "sync"} />
Remove size, as it conflicts with the styling of other icon buttons.

2024-03-13 10:18 UTC, janmarius commented on Src/WitsmlExplorer.Frontend/components/ContentViews/EditNumber.tsx
>          <Icon size={16} name={"arrowForward"} />
Remove size, as it conflicts with the styling of other icon buttons.

2024-03-13 10:18 UTC, janmarius commented on Src/WitsmlExplorer.Frontend/components/StyledComponents/Buttons.tsx
> +export const OutlinedIconButton = styled(Button)`
I think we can remove this one, as having several types of icon buttons in the application is not necessary.

2024-03-13 10:18 UTC, janmarius commented on Src/WitsmlExplorer.Frontend/components/StyledComponents/Buttons.tsx
> +export const StyledGhostButton = styled(Button)<{ colors: Colors }>`
Is IconButton a more descriptive name?

2024-03-14 11:05 UTC, eliasbruvik commented
Jan-Marius wants to handle everything in a Buttons-component, which requires more changes and makes this PR redundant.

2024-03-14 11:05 UTC, closed without merging