Cancel/Abort button for jobs in progress #2237
equinor/witsml-explorer pull request #2300
Opened 2024-03-13 10:47 UTC by robertbasti

[//]: # (Request Template Witsml Explorer)

[//]: # (Thank you for contributing to WITSML Explorer! Before submitting this PR, please fill in the following template.)

## Fixes
 This pull request fixes https://github.com/equinor/witsml-explorer/issues/2237

## Description
- preparation for cancelling a job by user,
- implementation of Downloading logs to CSV job

[//]: # (Please include a written summary of the changes and which issue is fixed. List any dependencies that are required for this change._)

## Type of change

[//]: # (Mark any of the types of change that apply.)

* [ ] Bugfix
* [ ] New feature (non-breaking change which adds functionality)
* [x] Enhancement of existing functionality
* [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
* [ ] This change requires a documentation update

## Impacted Areas in Application

[//]: # (List general components of the application that this PR will affect)

* [x] Frontend
* [x] API
* [ ] WITSML
* [ ] Other (please describe)

## Checklist:

[//]: # (Please tick all the boxes or remove the ones that aren't needed and explain why)

*Communication*
* [ ] I have made corresponding changes to the documentation
* [ ] PR affects application security

*Code quality*
* [x] I have self-reviewed my code
* [x] No new warnings are generated

*Test coverage*
* [] New code is covered by passing tests

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

2024-03-14 10:02 UTC, eliasbruvik requested changes

2024-03-14 10:02 UTC, eliasbruvik commented on Src/WitsmlExplorer.Api/HttpHandlers/JobHandler.cs
> +        public static IResult CancelToken(string jobId, IJobCache jobCache)
Rename to CancelJob

2024-03-14 10:02 UTC, eliasbruvik commented on Src/WitsmlExplorer.Api/HttpHandlers/JobHandler.cs
> +            return TypedResults.Ok();
Rather return a proper code for the cases where the job does not exist, and only OK if the cancel was successful.

2024-03-14 10:02 UTC, eliasbruvik commented on Src/WitsmlExplorer.Api/Jobs/Job.cs
> +        public virtual bool? IsCancelable { get; }
Maybe this should default to false instead of being nullable?

2024-03-14 10:02 UTC, eliasbruvik commented on Src/WitsmlExplorer.Api/Jobs/JobInfo.cs
> +        public bool? Cancelable { get; internal set; } = false;
I don't think this should be nullable, just either true or false like mentioned for Job. Also, can we keep the naming consistent and rename it to IsCancelable?

2024-03-14 10:02 UTC, eliasbruvik commented on Src/WitsmlExplorer.Frontend/components/ContextMenus/JobInfoContextMenu.tsx
> +    JobService.cancelJob(jobInfo.id, abortController.signal);
You are never using the abortController to send any signals, so it might as well just be removed.

2024-03-14 10:02 UTC, eliasbruvik commented on Src/WitsmlExplorer.Api/HttpHandlers/JobHandler.cs
> +            if (job != null)
I think we should also check that the job is cancelable.

2024-03-14 10:02 UTC, eliasbruvik commented on Src/WitsmlExplorer.Frontend/models/jobs/jobInfo.tsx
> +  cancelable?: boolean;
This shouldn't be nullable either. Then, you also need to add a default value for it in `getJobInfo` in `testUtils.tsx`.

2024-03-14 10:02 UTC, eliasbruvik commented on Src/WitsmlExplorer.Frontend/components/ContextMenus/JobInfoContextMenu.tsx
> +          disabled={jobInfo.cancelable === null || jobInfo.status !== "Started"}
Check if it is false instead of null.

2024-03-14 10:02 UTC, eliasbruvik commented on Src/WitsmlExplorer.Frontend/services/jobService.tsx
> +      return null;
Instead of returning null if the response is not ok, use `throwError` to display an error message. You can look at `serverService.tsx` to see an example.

2024-03-14 10:02 UTC, eliasbruvik commented on Src/WitsmlExplorer.Frontend/components/Modals/ReportModal.tsx
> +      showCancelButton={checkIfJobIsCancelable && !fetchedReport}
This is fine for when the modal is waiting for a report. But when the job is already fetched (like if I click on the report from the jobs view), the cancel button still shows. You should probably check the !fetchedReport first. Also, you have forgotten to call your checkIfJobIsCancelable (which is a function, and not a const).

2024-03-14 10:02 UTC, eliasbruvik commented on Src/WitsmlExplorer.Frontend/components/Modals/ReportModal.tsx
> +    const fetchData = async () => {
When the Job progress PR is merged, there is a hook we can use to get the jobInfo, which will remove the need for this fetch.

2024-03-15 09:51 UTC, robertbasti commented on Src/WitsmlExplorer.Api/HttpHandlers/JobHandler.cs
> +        public static IResult CancelToken(string jobId, IJobCache jobCache)
fixed

2024-03-15 09:51 UTC, robertbasti commented on Src/WitsmlExplorer.Api/HttpHandlers/JobHandler.cs
> +            return TypedResults.Ok();
fixed

2024-03-15 09:51 UTC, robertbasti commented on Src/WitsmlExplorer.Api/Jobs/Job.cs
> +        public virtual bool? IsCancelable { get; }
fixed

2024-03-15 09:51 UTC, robertbasti commented on Src/WitsmlExplorer.Api/Jobs/JobInfo.cs
> +        public bool? Cancelable { get; internal set; } = false;
fixed

2024-03-15 09:51 UTC, robertbasti commented on Src/WitsmlExplorer.Frontend/components/ContextMenus/JobInfoContextMenu.tsx
> +    JobService.cancelJob(jobInfo.id, abortController.signal);
fixed

2024-03-15 09:52 UTC, robertbasti commented on Src/WitsmlExplorer.Api/HttpHandlers/JobHandler.cs
> +            if (job != null)
fixed

2024-03-15 09:52 UTC, robertbasti commented on Src/WitsmlExplorer.Frontend/models/jobs/jobInfo.tsx
> +  cancelable?: boolean;
fixed

2024-03-15 09:52 UTC, robertbasti commented on Src/WitsmlExplorer.Frontend/components/ContextMenus/JobInfoContextMenu.tsx
> +          disabled={jobInfo.cancelable === null || jobInfo.status !== "Started"}
fixed

2024-03-15 09:52 UTC, robertbasti commented on Src/WitsmlExplorer.Frontend/services/jobService.tsx
> +      return null;
fixed

2024-03-15 09:52 UTC, robertbasti commented on Src/WitsmlExplorer.Frontend/components/Modals/ReportModal.tsx
> +      showCancelButton={checkIfJobIsCancelable && !fetchedReport}
fixed

2024-03-15 09:52 UTC, robertbasti commented on Src/WitsmlExplorer.Frontend/components/Modals/ReportModal.tsx
> +    const fetchData = async () => {
fixed

2024-03-15 12:21 UTC, eliasbruvik approved these changes
- [x] Read issue and PR
- [x] Pulled branch and manually tested
- [x] Verify that PR resolves issue
- [x] Reviewed the code

2024-03-15 12:24 UTC, merged