2195 refresh after batch update
equinor/witsml-explorer pull request #2322
Opened 2024-03-19 18:41 UTC by vaclavbasniar

[//]: # (Request Template Witsml Explorer)

[//]: # (Thank you for contributing to WITSML Explorer! Before submitting this PR, please fill in the following template.)

## Fixes 

[//]: #2195 (Write the GitHub issue number starting with #, or, for Equinor only, the Jira issue number starting with WE-)

This pull request fixes updating of search view after batch update in search view  #2195.

## Description

[//]: # (Please include a written summary of the changes and which issue is fixed. List any dependencies that are required for this change._)

On front end side:
* Added originJobType to RefreshAction to be able to determine job type in RefreshHandler. 
* Added ObjectOnWellbore list to RefreshAction to get a list of batch updated objects in RefreshHandler. 
* Added #refreshSearchFilter function to RefreshHandler, which invalidates search query and changed objects queries.
On API side:
* Added BatchModifyObjectsOnSearchWorker, which reuses BatchModifyObjectsOnWellboreWorker code with different RefreshAction type - returns list of changed objects.

## Type of change

[//]: # (Mark any of the types of change that apply.)

* [x] Bugfix
* [ ] New feature (non-breaking change which adds functionality)
* [x] Enhancement of existing functionality
* [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
* [ ] This change requires a documentation update

## Impacted Areas in Application

[//]: # (List general components of the application that this PR will affect)

* [x] Frontend
* [x] API
* [ ] WITSML
* [ ] Other (please describe)

## Checklist:

[//]: # (Please tick all the boxes or remove the ones that aren't needed and explain why)

*Communication*
* [ ] I have made corresponding changes to the documentation
* [ ] PR affects application security

*Code quality*
* [x] I have self-reviewed my code
* [x] No new warnings are generated

*Test coverage*
* [x] New code is covered by passing tests

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

2024-03-20 09:55 UTC, eliasbruvik requested changes
I commented a few suggestions for improvement which will reduce code duplication and avoid introducing originJobType to all the workers. As it needs to be tested, we might need to make some small adjustments in case it would lead to too many re-fetches, but I think it would be fine.

2024-03-20 09:55 UTC, eliasbruvik commented on Src/WitsmlExplorer.Api/Jobs/BatchModifyObjectsOnSearchJob.cs
I don't think we need this new job and worker. I think it's fine to change the ReturnAction returned from BatchModifyObjectsOnWellboreWorker to your new BatchRefreshObjects instead.

2024-03-20 09:55 UTC, eliasbruvik commented on Src/WitsmlExplorer.Api/Models/RefreshAction.cs
> +            OriginJobType = originJobType;
I think it would be better to not add originJobType. In the refreshHandler, I think we can rather invalidate the search queries for any filterType that has received an update regardless on the job type.

If I for example perform a search, then navigate to the object and change it manually in properties (not batch update), and then go back to the search, it would be nice if it was invalidated so that I get the updated search result.

2024-03-20 09:55 UTC, eliasbruvik commented on Src/WitsmlExplorer.Frontend/components/RefreshHandler.tsx
> +                  JobType.BatchModifyObjectsOnSearch
Instead of checking the jobType (as I think it shouldn't be a part of RefreshAction), it would be nice if we could:

* When the RefreshAction is of type BatchModify, loop through the objects, and run invalidateObject on each individual object. This way we would not only invalidate the search, but also each object after the batch update.
* In refreshWellboreObject, we should also run refreshSearchQuery so that if an object is updated, we would always make sure that the updated values are represented in the search regardless of how the object is updated.

2024-03-22 11:37 UTC, vaclavbasniar commented on Src/WitsmlExplorer.Api/Models/RefreshAction.cs
> +            OriginJobType = originJobType;
Removed and refresh condition changed.

2024-03-22 11:37 UTC, vaclavbasniar commented on Src/WitsmlExplorer.Frontend/components/RefreshHandler.tsx
> +                  JobType.BatchModifyObjectsOnSearch
Removed and refresh condition changed.

2024-03-22 11:38 UTC, vaclavbasniar commented on Src/WitsmlExplorer.Api/Jobs/BatchModifyObjectsOnSearchJob.cs
Removed and BatchModifyObjectsOnWellboreWorker updated.

2024-03-22 12:47 UTC, eliasbruvik requested changes
Good work, this is exactly what I had in mind. 

There's some extra logic to avoid re-fetching some queries if all the objects are already fetched. That logic does not currently take invalidation into consideration. Can you add this function to the end of `useGetObjectSearch.tsx`, and set `cachedAllObjects` in the `useGetObjectSearch` hook to use that function?

`const cachedAllObjects = getCachedAllObjects(queryClient, server.url, filterType);`

```
const getCachedAllObjects = (queryClient: QueryClient, serverUrl: string, filterType: ObjectFilterType) => {
  const allObjectsQueryKey = getObjectSearchQueryKey(serverUrl, filterType, "", true);
  const cachedState = queryClient.getQueryState(allObjectsQueryKey)
  if (cachedState?.isInvalidated) {
    return null;
  }
  return queryClient.getQueryData<ObjectSearchResult[]>(
    allObjectsQueryKey
  );
}
```

When that is added, the invalidation will cause a re-fetch even when we already have fetched all the objects which is what we want.

2024-04-02 10:52 UTC, eliasbruvik approved these changes
- [x] Read issue and PR
- [x] Pulled branch and manually tested
- [x] Verify that PR resolves issue
- [x] Reviewed the code

2024-04-03 12:59 UTC, merged