Add Cancellation for copy log jobs #2423
equinor/witsml-explorer pull request #2458
Opened 2024-06-04 10:40 UTC by robertbasti

[//]: # (Request Template Witsml Explorer)

[//]: # (Thank you for contributing to WITSML Explorer! Before submitting this PR, please fill in the following template.)

## Fixes 

[//]: # (Write the GitHub issue number starting with #, or, for Equinor only, the Jira issue number starting with WE-)

This pull request fixes #2423

## Description

Added an cancelation capability to all copy jobs.

## Type of change

[//]: # (Mark any of the types of change that apply.)

* [ ] Bugfix
* [ ] New feature (non-breaking change which adds functionality)
* [x] Enhancement of existing functionality
* [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
* [ ] This change requires a documentation update

## Impacted Areas in Application

[//]: # (List general components of the application that this PR will affect)

* [x] Frontend
* [x] API
* [ ] WITSML
* [ ] Desktop
* [ ] Other (please describe)

## Checklist:

[//]: # (Please tick all the boxes or remove the ones that aren't needed and explain why)

*Communication*
* [ ] I have made corresponding changes to the documentation
* [ ] PR affects application security

*Code quality*
* [x] I have self-reviewed my code
* [x] No new warnings are generated

*Test coverage*
* [x] New code is covered by passing tests

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

2024-06-05 09:13 UTC, eliasbruvik requested changes

2024-06-05 09:13 UTC, eliasbruvik commented on Src/WitsmlExplorer.Api/Workers/Copy/CopyComponentsWorker.cs
> +            // cancellationToken?.ThrowIfCancellationRequested();
Remove comment

2024-06-05 09:13 UTC, eliasbruvik commented on Src/WitsmlExplorer.Api/Workers/Copy/CopyLogDataWorker.cs
> +            if (job.JobInfo != null) job.JobInfo.Progress = progress;
Remove this line (duplicate of the one above)

2024-06-05 09:13 UTC, eliasbruvik commented on Src/WitsmlExplorer.Api/Workers/ReplaceComponentsWorker.cs
I wouldn't expect both statuses to be 'Cancelled'. Either the first one is 'Success' and the second is 'Cancelled', or the first one is 'Cancelled', and the second line is either not added at all, or 'Not Started'.
![image](https://github.com/equinor/witsml-explorer/assets/70512270/33b448b5-961e-4093-afdb-221a03e996ae)

2024-06-05 09:19 UTC, eliasbruvik requested changes

2024-06-05 09:19 UTC, eliasbruvik commented on Src/WitsmlExplorer.Api/Workers/Copy/CopyWithParentWorker.cs
Can you add some more info to the error message when you cancel CopyWithParents job? At least what kind of job was cancelled?

![image](https://github.com/equinor/witsml-explorer/assets/70512270/44a49112-55d1-4e0a-b901-c8110e09ee56)

Edit: Got the same message on CopyObjectsJob aswell.

2024-06-05 13:25 UTC, robertbasti commented on Src/WitsmlExplorer.Api/Workers/Copy/CopyComponentsWorker.cs
> +            // cancellationToken?.ThrowIfCancellationRequested();
fixed

2024-06-05 13:25 UTC, robertbasti commented on Src/WitsmlExplorer.Api/Workers/Copy/CopyLogDataWorker.cs
> +            if (job.JobInfo != null) job.JobInfo.Progress = progress;
fixed

2024-06-05 13:25 UTC, robertbasti commented on Src/WitsmlExplorer.Api/Workers/ReplaceComponentsWorker.cs
fixed

2024-06-05 13:25 UTC, robertbasti commented on Src/WitsmlExplorer.Api/Workers/Copy/CopyWithParentWorker.cs
fixed

2024-06-06 08:51 UTC, eliasbruvik approved these changes
*Reviewer checklist*
- [x] Read issue and PR
- [x] Pulled branch and manually tested
- [x] Verify that PR resolves issue
- [x] Reviewed the code

2024-06-06 09:02 UTC, merged