FIX-2476 Inform user when no active wells are available and inactive are hidden
equinor/witsml-explorer pull request #2484
Opened 2024-06-20 10:19 UTC by matusmlichsk

[//]: # (Request Template Witsml Explorer)

[//]: # (Thank you for contributing to WITSML Explorer! Before submitting this PR, please fill in the following template.)

## Fixes

[//]: # (Write the GitHub issue number starting with #, or, for Equinor only, the Jira issue number starting with WE-)

This pull request fixes #2476

## Description

[//]: # (Please include a written summary of the changes and which issue is fixed. List any dependencies that are required for this change._)

Inform user when no wells are available because of selected filter which hides inactive wells. Also user has possibility to disable this filter with direct single-click approach. 

## Type of change

[//]: # (Mark any of the types of change that apply.)

* [x] Bugfix
* [ ] New feature (non-breaking change which adds functionality)
* [ ] Enhancement of existing functionality
* [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
* [ ] This change requires a documentation update

## Impacted Areas in Application

[//]: # (List general components of the application that this PR will affect)

* [x] Frontend
* [ ] API
* [ ] WITSML
* [ ] Desktop
* [ ] Other (please describe)

## Checklist:

[//]: # (Please tick all the boxes or remove the ones that aren't needed and explain why)

*Communication*
* [ ] I have made corresponding changes to the documentation
* [ ] PR affects application security

*Code quality*
* [x] I have self-reviewed my code
* [x] No new warnings are generated

*Test coverage*
* [ ] New code is covered by passing tests

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

2024-06-20 12:01 UTC, eliasbruvik requested changes
Code looks clean and structured, just had a couple comments with stuff you were probably unaware of. :)

2024-06-20 12:01 UTC, eliasbruvik commented on Src/WitsmlExplorer.Frontend/components/Sidebar/InactiveWellsHiddenFilterHelper/InactiveWellsHiddenFilterHelper.tsx
> +Icon.add({ info_circle });
The icon is already imported in `Src\WitsmlExplorer.Frontend\styles\Icons.tsx`. For some unknow reason we are using camelcase names for our icons, so you should use `name="infoCircle"` below.

2024-06-20 12:01 UTC, eliasbruvik commented on Src/WitsmlExplorer.Frontend/components/Sidebar/InactiveWellsHiddenFilterHelper/InactiveWellsHiddenFilterHelper.tsx
> +    <Chip onDelete={handleClearFilterProperty}>
As this is the first chip we are using, the styling is not configured to adapt to light/dark mode. Can you make it adapt to dark mode?

Tip: If you want to avoid having to navigate to settings to toggle light/dark mode, you can create a `.env.development.local` file in `Src\Frontend`, and add `VITE_DARK_MODE_DEBUG=true`. This will allow you to use the hotkeys `SHIFT+TAB` to toggle between light and dark mode.

2024-06-20 12:24 UTC, matusmlichsk commented on Src/WitsmlExplorer.Frontend/components/Sidebar/InactiveWellsHiddenFilterHelper/InactiveWellsHiddenFilterHelper.tsx
> +    <Chip onDelete={handleClearFilterProperty}>
Will adapt that, thanks for hint.

2024-06-23 13:08 UTC, matusmlichsk commented on Src/WitsmlExplorer.Frontend/components/Sidebar/InactiveWellsHiddenFilterHelper/InactiveWellsHiddenFilterHelper.tsx
> +Icon.add({ info_circle });
fixed

2024-06-23 13:09 UTC, matusmlichsk commented on Src/WitsmlExplorer.Frontend/components/Sidebar/InactiveWellsHiddenFilterHelper/InactiveWellsHiddenFilterHelper.tsx
> +    <Chip onDelete={handleClearFilterProperty}>
dark mode adapted

2024-06-24 06:11 UTC, eliasbruvik approved these changes
*Reviewer checklist*
- [x] Read issue and PR
- [x] Pulled branch and manually tested
- [x] Verify that PR resolves issue
- [x] Reviewed the code

2024-06-24 06:28 UTC, merged