test
equinor/witsml-explorer pull request #2564
Opened 2024-10-08 09:24 UTC by robertbasti

[//]: # (Request Template Witsml Explorer)

[//]: # (Thank you for contributing to WITSML Explorer! Before submitting this PR, please fill in the following template.)

## Fixes

[//]: # (Write the GitHub issue number starting with #, or, for Equinor only, the Jira issue number starting with WE-)

This pull request fixes 

## Description

[//]: # (Please include a written summary of the changes and which issue is fixed. List any dependencies that are required for this change._)

## Type of change

[//]: # (Mark any of the types of change that apply.)

* [ ] Bugfix
* [ ] New feature (non-breaking change which adds functionality)
* [ ] Enhancement of existing functionality
* [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
* [ ] This change requires a documentation update

## Impacted Areas in Application

[//]: # (List general components of the application that this PR will affect)

* [ ] Frontend
* [ ] API
* [ ] WITSML
* [ ] Desktop
* [ ] Other (please describe)

## Checklist:

[//]: # (Please tick all the boxes or remove the ones that aren't needed and explain why)

*Communication*
* [ ] I have made corresponding changes to the documentation
* [ ] PR affects application security

*Code quality*
* [ ] I have self-reviewed my code
* [ ] No new warnings are generated

*Test coverage*
* [ ] New code is covered by passing tests

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

2024-10-17 14:01 UTC, eliasbruvik requested changes

2024-10-17 14:01 UTC, eliasbruvik commented on Src/WitsmlExplorer.Frontend/components/Modals/LogDataImportModal.tsx
Can this be shown only if a file has been uploaded?
![image](https://github.com/user-attachments/assets/65615816-13e5-40bb-9a7a-ee7a17447dc1)

2024-10-17 14:01 UTC, eliasbruvik commented on Src/WitsmlExplorer.Frontend/components/Modals/LogDataImportModal.tsx
The count is incorrect, maybe some mismatch with the index curve?
![image](https://github.com/user-attachments/assets/8c813fb1-1282-49e7-99a4-50f6398bc912)

2024-10-17 14:01 UTC, eliasbruvik commented on Src/WitsmlExplorer.Frontend/components/Modals/LogDataImportModal.tsx
We probably don't need to show this for the preview table. Just pass `showPanel={false}` to the ContentTable.
![image](https://github.com/user-attachments/assets/40994561-3f3f-49b4-9c1e-8ec27125f489)

2024-10-17 14:01 UTC, eliasbruvik commented on Src/WitsmlExplorer.Frontend/components/Modals/LogDataImportModal.tsx
After selecting a file where the index curve is not present, I don't get the _The target index curve needs to be present in the file_ warning you used to get. Instead, it's as if no file has been selected at all.

2024-10-17 14:01 UTC, eliasbruvik commented on Src/WitsmlExplorer.Frontend/components/Modals/LogDataImportModal.tsx
Maybe we should move the index curve format input box between where you select mnemonics and the limitations?

![image](https://github.com/user-attachments/assets/3d0a3c22-84c8-4a14-ab5c-f8d041f71aa7)

2024-10-17 14:01 UTC, eliasbruvik commented on Src/WitsmlExplorer.Frontend/components/Modals/LogDataImportModal.tsx
> +  const [allFileColumns, setAllFileColumns] = useState<ImportColumn[]>([]);
I think it would be easier to read and maintain if we don't have both _allUploadedFileData_ and _uploadedFileData_ as state variables (same for _uploadedFileColumns_ and _allFileColumns_. It's easier to maintain if we keep _uploadedFileData_, _uploadedFileColumns_ and _selectedMnemonics_ as state, and then add something like _filteredData_ and _filteredColumns_ (normal variables, without useState) that is calculated directly from the three state variables.

2024-10-17 14:01 UTC, eliasbruvik commented on Src/WitsmlExplorer.Frontend/components/Modals/LogDataImportModal.tsx
> +                // @ts-ignore. Variant is defined and exists in the documentation, but not in the type definition.
I don't think we need that ts-ignore anymore. Guess it has been fixed after upgrading that library at some point.

2024-10-17 14:01 UTC, eliasbruvik commented on Src/WitsmlExplorer.Frontend/components/Modals/LogDataImportModal.tsx
The file is getting a bit large. Would it make sense to move any of the functions at the bottom to separate files? Maybe divide it a bit by what the functionality does if there is any logic way to divide it up.

2024-10-17 17:22 UTC, robertbasti commented on Src/WitsmlExplorer.Frontend/components/Modals/LogDataImportModal.tsx
fixed

2024-10-17 17:59 UTC, robertbasti commented on Src/WitsmlExplorer.Frontend/components/Modals/LogDataImportModal.tsx
fixed

2024-10-17 18:00 UTC, robertbasti commented on Src/WitsmlExplorer.Frontend/components/Modals/LogDataImportModal.tsx
> +                // @ts-ignore. Variant is defined and exists in the documentation, but not in the type definition.
fixed

2024-10-18 06:59 UTC, robertbasti commented on Src/WitsmlExplorer.Frontend/components/Modals/LogDataImportModal.tsx
> +  const [allFileColumns, setAllFileColumns] = useState<ImportColumn[]>([]);
we agreed not to change that for now

2024-10-18 08:24 UTC, robertbasti commented on Src/WitsmlExplorer.Frontend/components/Modals/LogDataImportModal.tsx
fixed

2024-10-18 11:56 UTC, robertbasti commented on Src/WitsmlExplorer.Frontend/components/Modals/LogDataImportModal.tsx
fixed

2024-10-18 12:31 UTC, robertbasti commented on Src/WitsmlExplorer.Frontend/components/Modals/LogDataImportModal.tsx
fixed

2024-10-18 13:44 UTC, eliasbruvik requested changes
Maybe change this warning a bit? I suggest something changing to something like this.

Current:
```
Mnemonics with the same names (in brackets are numbers of occurences): RPM TOT(2) TEMP OUT(2) A(3) . Duplicate names were automatically changed by adding numbers as suffix in brackets.
```
New:
```
Found multiple mnemonics with the same name: <list of duplicates as before> . Duplicate names were automatically changed by adding numbers as suffix in parenthesis.
```

2024-10-21 06:50 UTC, eliasbruvik approved these changes
*Reviewer checklist*
- [x] Read issue and PR
- [x] Pulled branch and manually tested
- [x] Verify that PR resolves issue
- [x] Reviewed the code

2024-10-21 07:13 UTC, merged