Ultra-compact mode ui bug fixes #2576
equinor/witsml-explorer pull request #2595
Opened 2024-11-11 13:07 UTC by matusmlichsk

[//]: # (Request Template Witsml Explorer)

[//]: # (Thank you for contributing to WITSML Explorer! Before submitting this PR, please fill in the following template.)

## Fixes

[//]: # (Write the GitHub issue number starting with #, or, for Equinor only, the Jira issue number starting with WE-)

This pull request fixes issue #2576 

## Description

[//]: # (Please include a written summary of the changes and which issue is fixed. List any dependencies that are required for this change._)

- tabs in query editor are fixed height without overflow
- data grid switcher position changed
- no console warns connected with transient styled component props
- isLoading button miss-align on login fixed
- breadcrumbs properly aligned

## Type of change

[//]: # (Mark any of the types of change that apply.)

* [x] Bugfix
* [ ] New feature (non-breaking change which adds functionality)
* [ ] Enhancement of existing functionality
* [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
* [ ] This change requires a documentation update

## Impacted Areas in Application

[//]: # (List general components of the application that this PR will affect)

* [x] Frontend
* [ ] API
* [ ] WITSML
* [ ] Desktop
* [ ] Other (please describe)

## Checklist:

[//]: # (Please tick all the boxes or remove the ones that aren't needed and explain why)

*Communication*
* [ ] I have made corresponding changes to the documentation
* [ ] PR affects application security

*Code quality*
* [x] I have self-reviewed my code
* [x] No new warnings are generated

*Test coverage*
* [ ] New code is covered by passing tests

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

2024-11-12 08:15 UTC, eliasbruvik requested changes

2024-11-12 08:15 UTC, eliasbruvik commented on Src/WitsmlExplorer.Frontend/components/ContentViews/QueryView/components/QueryOptions/DataGridSwitch/DataGridSwitch.tsx
> +        label="Use data grid view"
Hard to read in dark mode: 
![image](https://github.com/user-attachments/assets/f817e0ec-f26e-4cd3-bc1e-215b691d59c0)

2024-11-12 08:15 UTC, eliasbruvik commented on Src/WitsmlExplorer.Frontend/components/Sidebar/SearchFilter/SearchFilter.tsx
> +const SearchField = styled(TextField)<{ colors: Colors; $isCompact: boolean }>`
I'm getting a syntax warning for an extra } at the end of SearchField.

2024-11-12 08:15 UTC, eliasbruvik commented on Src/WitsmlExplorer.Frontend/components/Breadcrumbs.tsx
Seems like the problem with the breadcrumbs happens on both my monitors if I select 100% scaling, but it looks good on 125%. Adding this to the style in EdsBreadcrumbs.Breadcrumb makes it a bit better, but you might have a better idea.
```
lineHeight: "16px",
display: "inline-flex",
```

How it looks on 100%:
![image](https://github.com/user-attachments/assets/e853ea83-2a7a-4842-8a87-624252e2de0d)

2024-11-15 10:44 UTC, matusmlichsk commented on Src/WitsmlExplorer.Frontend/components/Sidebar/SearchFilter/SearchFilter.tsx
> +const SearchField = styled(TextField)<{ colors: Colors; $isCompact: boolean }>`
fixed

2024-11-15 10:44 UTC, matusmlichsk commented on Src/WitsmlExplorer.Frontend/components/ContentViews/QueryView/components/QueryOptions/DataGridSwitch/DataGridSwitch.tsx
> +        label="Use data grid view"
fixed

2024-11-15 10:45 UTC, matusmlichsk commented on Src/WitsmlExplorer.Frontend/components/Breadcrumbs.tsx
should be fixed

2024-11-15 13:34 UTC, eliasbruvik approved these changes
*Reviewer checklist*
- [x] Read issue and PR
- [x] Pulled branch and manually tested
- [x] Verify that PR resolves issue
- [x] Reviewed the code

2024-11-15 13:46 UTC, merged