Disable las file download for selected rows #2602
equinor/witsml-explorer pull request #2607
Opened 2024-11-25 15:44 UTC by robertbasti

[//]: # (Request Template Witsml Explorer)

[//]: # (Thank you for contributing to WITSML Explorer! Before submitting this PR, please fill in the following template.)

## Fixes

This pull request fixes #2602

## Description

Disable las file download for selected row

## Type of change

[//]: # (Mark any of the types of change that apply.)

* [ ] Bugfix
* [ ] New feature (non-breaking change which adds functionality)
* [x] Enhancement of existing functionality
* [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
* [ ] This change requires a documentation update

## Impacted Areas in Application

[//]: # (List general components of the application that this PR will affect)

* [x] Frontend
* [x] API
* [ ] WITSML
* [ ] Desktop
* [ ] Other (please describe)

## Checklist:

[//]: # (Please tick all the boxes or remove the ones that aren't needed and explain why)

*Communication*
* [ ] I have made corresponding changes to the documentation
* [ ] PR affects application security

*Code quality*
* [x] I have self-reviewed my code
* [x] No new warnings are generated

*Test coverage*
* [x] New code is covered by passing tests

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

2024-11-26 07:31 UTC, eliasbruvik requested changes

2024-11-26 07:31 UTC, eliasbruvik commented on Src/WitsmlExplorer.Frontend/components/Modals/DownloadOptionsSelectionModal.tsx
> +  let downloadFormat: DownloadFormat = DownloadFormat.Csv;
Can you change these to use useState instead?

2024-11-26 07:31 UTC, eliasbruvik commented on Src/WitsmlExplorer.Frontend/components/Modals/DownloadOptionsSelectionModal.tsx
> +          {visibleFileTypeSelection && (
Instead of hiding it entirely, does it make more sense to disable the LAS option? That way the user would know what file type to expect.

2024-11-26 14:00 UTC, robertbasti commented on Src/WitsmlExplorer.Frontend/components/Modals/DownloadOptionsSelectionModal.tsx
> +  let downloadFormat: DownloadFormat = DownloadFormat.Csv;
fixed

2024-11-27 07:49 UTC, eliasbruvik requested changes

2024-11-27 07:49 UTC, eliasbruvik commented on Src/WitsmlExplorer.Frontend/components/Modals/DownloadOptionsSelectionModal.tsx
> +  const [selectedDownloadOption, setSelectedDownloadOption] = useState<string>(
Change type to _<DownloadOptions>_

2024-11-27 07:49 UTC, eliasbruvik commented on Src/WitsmlExplorer.Frontend/components/Modals/DownloadOptionsSelectionModal.tsx
> +  const [selectedDownloadFormat, setSelectedDownloadFormat] = useState<string>(
Change type to <DownloadFormat>

2024-11-27 08:35 UTC, robertbasti commented on Src/WitsmlExplorer.Frontend/components/Modals/DownloadOptionsSelectionModal.tsx
> +  const [selectedDownloadOption, setSelectedDownloadOption] = useState<string>(
fixed

2024-11-27 08:35 UTC, robertbasti commented on Src/WitsmlExplorer.Frontend/components/Modals/DownloadOptionsSelectionModal.tsx
> +  const [selectedDownloadFormat, setSelectedDownloadFormat] = useState<string>(
fixed

2024-11-27 08:36 UTC, eliasbruvik approved these changes
*Reviewer checklist*
- [x] Read issue and PR
- [x] Pulled branch and manually tested
- [x] Verify that PR resolves issue
- [x] Reviewed the code

2024-11-27 08:42 UTC, merged